language: julia
julia:
    - release
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("CompEcon")'
    - julia -e 'Pkg.test("CompEcon", coverage=true)'
after_success:
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("CompEcon")); Pkg.add("Coverage"); using Coverage; proc = process_folder(); Coveralls.submit(proc); Codecov.submit(proc)'; fi
